remove some messages

diff --git a/err/src/errXmlToH b/err/src/errXmlToH
--- a/err/src/errXmlToH
+++ b/err/src/errXmlToH
@@ -2,7 +2,7 @@
 #*******************************************************************************
 # JMMC project
 #
-# "@(#) $Id: errXmlToH,v 1.2 2004-06-24 07:42:01 mella Exp $"
+# "@(#) $Id: errXmlToH,v 1.3 2004-06-24 07:49:15 mella Exp $"
 #
 # who       when         what
 # --------  -----------  -------------------------------------------------------
@@ -65,32 +65,31 @@ GETFILE()
 if [ $# != 2 ];
 then
 	echo "USAGE : $0 ../errors/<mod>Errors.xml ../include/<mod>Errors.h"
-
 else
 	#XSD & XSL declaration files
-	GETFILE "errXmlToH.xsd"
-	if [ "$fullPath" = "NULL" ]
-	then
-		echo "XSD Schema File Not Found"
-		exit 1;
-	fi
-	schema="$fullPath"
-	
+    GETFILE "errXmlToH.xsd"
+    if [ "$fullPath" = "NULL" ]
+    then
+        echo "XSD Schema File Not Found"
+        exit 1;
+    fi
+    schema="$fullPath"
+
     GETFILE "errXmlToH.xsl"
-	if [ "$fullPath" = "NULL" ]
-	then
-		echo "XSL Transformation File Not Found"
-		exit 1;
-	fi
-	xslt="$fullPath"
+    if [ "$fullPath" = "NULL" ]
+    then
+        echo "XSL Transformation File Not Found"
+        exit 1;
+    fi
+    xslt="$fullPath"
 
-	# Check Xml file validity
-	res=`xmllint --noout --schema $schema $1`
-	val="$1 validates"
+    # Check Xml file validity
+    res=`xmllint --noout --schema $schema $1 2> /dev/null`
+    val="$1 validates"
 
-	if [ "$res" = "$val" ];
-	then
-		echo "$val"
+    if [ "$res" = "$val" ];
+    then
+        echo "$val"
 
         # if output file exists then exit
         if [ -a $2 ];
@@ -99,16 +98,13 @@ else
             echo "Please change filename and run it again.";
             exit 1;
         fi
-        
-		xsltproc $xslt $1 > $2
-		echo "Error header file $2 created successfully."
-	else
-		echo "$res"
-		echo "Sorry, validation error. You need to modify $1."
-	fi
 
-	#Delete temporary files
-	rm -rf $xmlVal
+        xsltproc $xslt $1 > $2
+        echo "Error header file $2 created successfully."
+    else
+        echo "$res"
+        echo "Sorry, validation error. You need to modify $1."
+    fi
 fi
 
 exit 0;
