Add exit values 0|1

diff --git a/err/src/errXmlToH b/err/src/errXmlToH
--- a/err/src/errXmlToH
+++ b/err/src/errXmlToH
@@ -2,7 +2,7 @@
 #*******************************************************************************
 # JMMC project
 #
-# "@(#) $Id: errXmlToH,v 1.1 2004-06-24 07:24:31 mella Exp $"
+# "@(#) $Id: errXmlToH,v 1.2 2004-06-24 07:42:01 mella Exp $"
 #
 # who       when         what
 # --------  -----------  -------------------------------------------------------
@@ -25,6 +25,7 @@
 #   ENVIRONMENT
 #
 #   RETURN VALUES
+#   errXmlToH exits with a value of 0 on success or 1 on failure.
 #
 #   CAUTIONS
 #
@@ -71,7 +72,7 @@ else
 	if [ "$fullPath" = "NULL" ]
 	then
 		echo "XSD Schema File Not Found"
-		exit
+		exit 1;
 	fi
 	schema="$fullPath"
 	
@@ -79,7 +80,7 @@ else
 	if [ "$fullPath" = "NULL" ]
 	then
 		echo "XSL Transformation File Not Found"
-		exit
+		exit 1;
 	fi
 	xslt="$fullPath"
 
@@ -110,6 +111,7 @@ else
 	rm -rf $xmlVal
 fi
 
+exit 0;
 
 
 
